#!/bin/bash
###########
inv3x3(){
    #usage: read a b c d e f g h i <<<$(inv3x3 x0 x1 x2 )
    # where [ a b c ]
    #       [ d e f ]
    #       [ g h i ]
    x0=$1
    x1=$2
    x2=$3
    det=$(awk 'BEGIN {print ('$x1'-'$x2')*('$x0'-'$x1')*('$x0'-'$x2')}')
    a=$(awk 'BEGIN {print ('$x1'-'$x2')/'$det'}')
    b=$(awk 'BEGIN {print ('$x2'-'$x0')/'$det'}')
    c=$(awk 'BEGIN {print ('$x0'-'$x1')/'$det'}')
    d=$(awk 'BEGIN {print ('$x2'^2-'$x1'^2)/'$det'}')
    e=$(awk 'BEGIN {print ('$x0'^2-'$x2'^2)/'$det'}')
    f=$(awk 'BEGIN {print ('$x1'^2-'$x0'^2)/'$det'}')
    g=$(awk 'BEGIN {print ('$x2'*('$x1'^2)-'x1'*('$x2'^2))/'$det'}')
    h=$(awk 'BEGIN {print ('$x2'*('$x0'^2)-'x0'*('$x2'^2))/'$det'}')
    i=$(awk 'BEGIN {print ('$x0'*('$x1'^2)-'x1'*('$x0'^2))/'$det'}')
    foo=$(awk 'BEGIN {print ('$x1'^2)*'$x2'}')
    bar=$(awk 'BEGIN {print ('$x2'^2)*'$x1'}')
    echo $g $h $i
    echo foo: $foo
    echo bar: $bar
    echo wut: $wut
    exit
    echo $a $b $c $d $e $f $g $h $i
}
###########

###########
mult3x3by3x1(){
    #usage: read a b c <<<$(inv3x3 x0 x1 x2 x3 x4 x5 x6 x7 x8 y0 y1 y2 )
    # where [a] [ x0 x1 x2 ][y0]
    #       [b]=[ x3 x4 x5 ][y1]
    #       [c] [ x6 x7 x8 ][y2]
    x0=$1
    x1=$2
    x2=$3
    x3=$4
    x4=$5
    x5=$6
    x6=$7
    x7=$8
    x8=$9
    y0=${10}
    y1=${11}
    y2=${12}
    echo $x0 $x1 $x2 $x3 $x4 $x5 $x6 $x7 $x8 $y0 $y1 $y2

    a=$(awk 'BEGIN {print 'x0'*'y0'+'x1'*'y1'+'x2'*'y2'}')
    b=$(awk 'BEGIN {print 'x3'*'y0'+'x4'*'y1'+'x5'*'y2'}')
    c=$(awk 'BEGIN {print 'x6'*'y0'+'x7'*'y1'+'x8'*'y2'}')
    echo $a $b $c
}
###########

###########
fd=meantheta_sumsigma_j28jp32_dtheta1.dat

totsum=$(awk '$1>=0 {print $1,$2}' $fd | awk '{sum=sum+$2}END{print sum}')

read sum1 x2 <<<$(awk '$1>=0 {print $1,$2}' $fd | awk 'BEGIN {sum=0} \
    {if(sum/'$totsum'<2/3) {sum=sum+$2;thispoint=$1}}\
        END {print sum,thispoint}')

x1=$(awk 'BEGIN {if('$sum1'/'$totsum'>2/3){print '$x2'-1}else{print '$x2'+1}}')
x0=$((x1-1))
echo $x0 $x1 $x2
read y0 y1 y2 <<<$(sed -n '/^'$x2' \|^'$x1' \|^'$x0' [0-9]*\.[0-9]*/p' $fd | awk '{print $2}')
sum2=$(awk 'BEGIN {if('$x2'>'$x1'){print '$sum1'+'$y2'}else{print '$sum1'-'$y2'}}')
sum0=$(awk 'BEGIN {print '$sum1'-'$y1'}')


echo 0: $x0,$y0 -\>$sum0
echo 1: $x1,$y1 -\>$sum1
echo 2: $x2,$y2 -\>$sum2

#read a b c d e f g h i <<<$(inv3x3 $x0 $x1 $x2)
inv3x3 $x0 $x1 $x2
echo $y0 $y1 $y2
#read a b c <<<$(mult3x3by3x1 $a $b $c $d $e $f $g $h $i $y0 $y1 $y2)
mult3x3by3x1 $a $b $c $d $e $f $g $h $i $y0 $y1 $y2
dt=$(awk 'BEGIN {print ((2/3)*'$totsum'-'$sum2')*(('$x1'-'$x2')/('$sum1'-'$sum2'))+'$x2'}')
echo a=$a b=$b c=$c
echo dt=$dt
