#!/bin/bash


###############
#FUNCTION DEFS#
###############

###############
dj_singlem_plot(){
    dj=1
    djmax=4
    while [ $dj -le $djmax ]; do
        echo "#!/usr/local/gnuplot
        set term postscript eps enhanced
        fd='alldata.dat'
        " >$plotfile

        cat $fd | awk '$5=='$dj' {print $1,$2,$3,$4,$5,$6,$7}'>$tmp1file
        # $tmp1file fileds: same as alldata.dat
        # m, j, mp, jp, dj, dtheta, sigma

        m=$((-$dj))
        while [ $m -le $dj ]; do
            ofile=m$m\_dj$dj\_dthetavsigma.ps
            echo "
            set xlabel '{/Symbol s}'
            set ylabel '{/Symbol D}{/Symbol q}'
            set title 'dj=$dj,m=$m'
            plot '$tmp1file' u 7:(\$1==$m?\$6:0/1)

            set output '$ofile'
            replot
            ">>$plotfile
            let m=m+1
        done
        gnuplot <$plotfile >/dev/null
        let dj=dj+1
    done
}
###############

###############
tmp1_for_djdmplotfun(){
    rm $tmp1file
    dj=1
    djmax=4
    while [ $dj -le $djmax ]; do
        echo dj=$dj
        cat $fd | awk '$5=='$dj' {print $3-$1,$5,$6,$7}'>>$tmp1file
        # $tmp1file fields: dm, dj, dtheta, sigma
        let dj=dj+1
    done
}
###############

###############
dj_dm_plot(){
    dj=1
    djmax=4
    while [ $dj -le $djmax ]; do
        echo dj=$dj

        for dm in $(awk '{print $1}' $tmp1file|awk '!seen[$0]++'); do
            echo dm=$dm
            ofile=dm$dm\_dj$dj\_dthetavsigma.ps
            echo "#!/usr/local/gnuplot
            set term postscript eps enhanced
            fd='alldata.dat'

            set xlabel '{/Symbol s}'
            set ylabel '{/Symbol D}{/Symbol q}'
            set title 'dj=$dj,dm=$dm'
            plot '$tmp1file' u 4:(\$1==$dm&&\$2==$dj?\$3:0/1)

            set output '$ofile'
            replot
            ">$plotfile
            gnuplot <$plotfile >/dev/null
        done
        let dj=dj+1
    done
}
###############

###############
anglebins(){
    dj=1
    djmax=4
    infile=$tmp1file
    tmpfile=deleteme
    nbins=27
    scale=1
    N=0
    while [ $dj -le $djmax ];do
        echo dj=$dj
        while [ $N -le $nbins ]; do
            lbin=$(($scale*$N))
            ubin=$(($lbin+$scale))
            if [ $N -eq 0 ]; then
                foo[N]=$(awk '$2=='$dj'&&($3<'$ubin'&&$3>'$((-$ubin))') {sum=sum+$4} END {print sum}' $infile)
            else
                foo[N]=$(awk '$2=='$dj'&&($3<'$ubin'&&$3>'$((-$ubin))')&&($3>'$lbin'||$3<'$((-lbin))') {sum=sum+$4} END {print sum}' $infile)
            fi
            let N=N+1
        done
        foo[N]=$(awk '$2=='$dj'&&($3>'$ubin'||$3<'$((-ubin))') {sum=sum+$4} END {print sum}' $infile)
        echo $dj ${foo[*]} >>$tmpfile
        let dj=dj+1
        N=0
    done
    awk '{for(c=1;c<=NF;c++){a[c,NR]=$c};if(max_nf<NF){max_nf=NF};}END{for(c=1;c<=max_nf;c++){for(r=1;r<=NR;r++){if(r==1){printf("%i %s ",1*(c-1),a[c,r]);}else{printf("%s ",a[c,r]);}}print ""}}' $tmpfile >>normbindata
}
###############

###############
allangles(){
    dj=$(($jp-$j))
    infile=datfiles/jmp_j$j\_jp$jp\_dj$dj\.dat
    ofile=foofile
    rm $plotfile
    sed '/#/d' $infile|awk '{t=$1/sqrt('$j'*('$j'+1));tp=$2/sqrt('$jp'*('$jp'+1));dt=atan2(sqrt(1-tp*tp),tp)-atan2(sqrt(1-t*t),t);print dt*180/3.141592654,$3}'|sed '/nan/d' >$ofile

    nbins=45
    t=-180
    scale=$((360/$nbins))
    N=0
    while [ $t -lt 180 ]; do
        lbin=$t
        ubin=$(($t+$scale))

        if [ $N -eq 0 ]; then
            foo=$(awk '($1<='$ubin') {count++} END {print count}' $ofile)
        else
            foo=$(awk '($1<='$ubin')&&($1>'$lbin') {count++} END {print count}' $ofile)
        fi

        t=$ubin
        let N=N+1
        echo $lbin\to$ubin $foo>>$plotfile
    done
    
    rm $ofile $plotfile
}
###############

###############
alldm(){
    dj=$(($jp-$j))
    infile=datfiles/jmp_j$j\_jp$jp\_dj$dj\.dat
    ofile=dmdatfile
    pfile=dmplotfile
    rm $pfile $ofile
    echo \#dm num_dm >$pfile
    sed '/#/d' $infile|awk '{print $2-$1,$3}'>$ofile

    for dm in $(awk '{print $1}' $ofile|awk '!seen[$0]++'); do
        ndm=$(awk '$1=='$dm' {count++} END {print count}' $ofile)
        echo $dm $ndm >>$pfile
    done

    opfile=hist_dm_j$j\jp$jp\.ps
    echo "set terminal postscript eps enhanced
    set xlabel '{/Symbol D}m'
    set ylabel 'count'
    set title 'j=$j, jp=$jp'
    plot '$pfile' with impulse
    replot '$pfile' title ''
    set output '$opfile'
    replot">>$plotfile

    gnuplot <$plotfile >/dev/null 2>&1
    
    rm $ofile $pfile
}
###############

###############
weightedangles(){
    dj=$(($jp-$j))
    infile=datfiles/jmp_j$j\_jp$jp\_dj$dj\.dat
    ofile=foofile
    pfile=thplotfile
    rm $pfile $ofile $plotfile
    sed '/#/d' $infile|awk '{t=$1/sqrt('$j'*('$j'+1));tp=$2/sqrt('$jp'*('$jp'+1));dt=atan2(sqrt(1-tp*tp),tp)-atan2(sqrt(1-t*t),t);print dt*180/3.141592654,$3}'|sed '/nan/d' >$ofile

    nbins=45
    t=-180
    scale=$((360/$nbins))
    N=0
    while [ $t -lt 180 ]; do
        lbin=$t
        ubin=$(($t+$scale))

        if [ $N -eq 0 ]; then
            foo=$(awk '($1<='$ubin') {sum=sum+$2} END {print sum}' $ofile)
        else
            foo=$(awk '($1<='$ubin')&&($1>'$lbin') {sum=sum+$2} END {print sum}' $ofile)
        fi

        t=$ubin
        let N=N+1
        echo $lbin\to$ubin $foo>>$pfile
    done

    opfile=hist_wth_j$j\jp$jp\.ps
    echo "set terminal postscript eps enhanced
    set style data histogram
    set xtic rotate -90
    set xlabel '{/Symbol D}{/Symbol q}'
    set ylabel 'sum of {/Symbol s}s'
    set title 'j=$j, jp=$jp'
    plot '$pfile' u 2:xtic(1)
    set output '$opfile'
    replot">>$plotfile

    gnuplot <$plotfile >deleteme1
}
###############

###############
weighteddm(){
    dj=$(($jp-$j))
    infile=datfiles/jmp_j$j\_jp$jp\_dj$dj\.dat
    ofile=dmdatfile
    pfile=dmplotfile
    rm $pfile $ofile $plotfile
    echo \#dm num_dm >$pfile
    sed '/#/d' $infile|awk '{print $2-$1,$3}'>$ofile

    for dm in $(awk '{print $1}' $ofile|awk '!seen[$0]++'); do
        ndm=$(awk '$1=='$dm' {sum=sum+$2} END {print sum}' $ofile)
        echo $dm $ndm >>$pfile
    done

    opfile=hist_wdm_j$j\jp$jp\.ps
    echo "set terminal postscript eps enhanced
    set xlabel '{/Symbol D}m'
    set ylabel 'sum of {/Symbol s}s'
    set title 'j=$j, jp=$jp'
    plot '$pfile' u 1:2 with impulse
    replot '$pfile' u 1:2 title ''
    set output '$opfile'
    replot">>$plotfile

    gnuplot <$plotfile >/dev/null 2>&1
}
###############

###############
#  MY SCRIPT  #
###############
fd=alldata.dat
tmp1file=tmp1

plotfile=plotme3
rm $plotfile
j=8
jp=10
weightedangles
weighteddm
j=8
jp=11
weightedangles
weighteddm
j=20
jp=22
weightedangles
weighteddm
j=20
jp=23
weightedangles
weighteddm
j=35
jp=37
weightedangles
weighteddm
j=35
jp=38
weightedangles
weighteddm
