#!/bin/bash
j=1
dj=1
max=40
srcdir=/home/ashley/Documents/LeHigh/FortranResources/newdata/Ep002mf5i-50b.blam
srcdir=/home/ashley/Documents/LeHigh/FortranResources/newdata/Arp002-5i-40-384J-5.blam
echo $srcdir

while [ $dj -lt $(($max-1)) ]; do
    echo running dj=$dj
    while [ $j -lt $(($max-$dj+1)) ]; do
        # initialize parameters
        jp=$(($j+$dj))
        rawfile=datfilesAr/jmp_j$j\_jp$jp\_dj$dj\.dat
        scfile=scthetasAr/th_j$j\_jp$jp\_dj$dj\.dat
#        o2file=cp$rawfile

        # calculate datfile/jmp*
        echo $j $jp|../calcmm $srcdir $rawfile>/dev/null
#        echo \#x y z>$o2file
#        sed '/# [0-9]*/d' $rawfile | sed 's/#/ /g' | awk '{print $1,$2,$3}'>>$o2file

        # get semiclassical model for thetas
        ../dthetabar $srcdir $scfile $j $jp>/dev/null
        let j=j+1
    done
    j=1
    let dj=dj+1
done
