#!/bin/bash
j=1
dj=1
max=50
srcdir=/home/ashley/Documents/LeHigh/FortranResources/newdata/Ep002mf5i-50b.blam

while [ $dj -lt $(($max-1)) ]; do
    while [ $j -lt $(($max-$dj+1)) ]; do
        jp=$(($j+$dj))
        jbar=$(awk "BEGIN {print ("$j"+"$jp")/2}")
        if [ "$jbar" -eq "$jbar" ] 2>/dev/null; then
            jbstr=$jbar
        else
            jbstr=$(echo "$jbar"|sed 's/\./d/g')
        fi

        ofile=jmp_jb$jbstr\_dj$dj\.dat
        echo $j $jp|../calcmm $srcdir $ofile>/dev/null
        let j=j+1
    done
    j=0
    let dj=dj+1
done
