#!/bin/bash


###############
#FUNCTION DEFS#
###############

###############
dj_singlem_plot(){
    dj=1
    djmax=4
    while [ $dj -le $djmax ]; do
        echo "#!/usr/local/gnuplot
        set term postscript eps enhanced
        fd='alldata.dat'
        " >plotme

        cat $fd | awk '$5=='$dj' {print $1,$2,$3,$4,$5,$6,$7}'>tmp1

        m=$((-$dj))
        while [ $m -le $dj ]; do
            ofile=m$m\_dj$dj\_dthetavsigma.ps
            echo "
            set xlabel '{/Symbol s}'
            set ylabel '{/Symbol D}{/Symbol q}'
            set title 'dj=$dj,m=$m'
            plot 'tmp1' u 7:(\$1==$m?\$6:0/1)

            set output '$ofile'
            replot
            ">>plotme
            let m=m+1
        done
        gnuplot <plotme >/dev/null
        let dj=dj+1
    done
}
###############

###############
dj_dm_plot(){
    dj=1
    djmax=4
    while [ $dj -le $djmax ]; do
        echo dj=$dj

        for dm in $(awk '{print $1}' tmp1|awk '!seen[$0]++'); do
            echo dm=$dm
            ofile=dm$dm\_dj$dj\_dthetavsigma.ps
            echo "#!/usr/local/gnuplot
            set term postscript eps enhanced
            fd='alldata.dat'

            set xlabel '{/Symbol s}'
            set ylabel '{/Symbol D}{/Symbol q}'
            set title 'dj=$dj,dm=$dm'
            plot 'tmp1' u 4:(\$1==$dm&&\$2==$dj?\$3:0/1)

            set output '$ofile'
            replot
            ">plotme
            gnuplot <plotme >/dev/null
        done
        m=$((-$dj))
        let dj=dj+1
    done
}
###############

###############
#  MY SCRIPT  #
###############
fd=alldata.dat
dj_dm_plot

