#!/bin/bash


fd=alldata.dat
dj=1
djmax=4
while [ $dj -le $djmax ]; do
    echo "#!/usr/local/gnuplot
    set term postscript eps enhanced
    fd='alldata.dat'
    " >plotme

    cat $fd | awk '$5=='$dj' {print $1,$2,$3,$4,$5,$6,$7}'>tmp1

    m=$((-$dj))
    while [ $m -le $dj ]; do
        ofile=m$m\_dj$dj\_dthetavsigma.ps
        echo "
        set xlabel '{/Symbol s}'
        set ylabel '{/Symbol D}{/Symbol q}'
        set title 'dj=$dj,m=$m'
        plot 'tmp1' u 7:(\$1==$m?\$6:0/1)

        set output '$ofile'
        replot
        ">>plotme
        let m=m+1
    done
    gnuplot <plotme >/dev/null
    let dj=dj+1
done
