#!/bin/bash
# output##_## are DTheta values

filelist=(output15_11 output15_13 output18_16 output18_17 output25_21)

for i in ${filelist[@]}; do
    ../main $i
done

gnuplot -persistent < plotscript

#filelist2=(dq15-11.dat dq15-13.dat dq18-16.dat dq18-17.dat)

#for i in ${filelist2[@]}; do
#    echo $i
#done

#cd ../dkData
#gnuplot -persistent < plotscript
