#!/bin/bash

# put the j and jp values in the right order
if [ $1 -gt $2 ]; then
    j=$1
    jp=$2
elif [ $1 -lt $2 ]; then
    j=$2
    jp=$1
fi

Btheta=normBtheta\_$j\_$jp\.dat
Blambda=normBlambda\_$j\_$jp\.dat
echo Bt=$Btheta
echo Bl=$Blambda

# write the gnuplot commands
echo "
#!/usr/local/gnuplot
set samples 10000

# B(theta)*sin(theta) vs theta
plot '$Btheta' using 1:(\$2*sin(\$1*pi/180)) with lines smooth csplines

# B[lambda]*sin(theta->lambda)
replot '$Blambda' using 3:(\$2*sin(\$3*pi/180))
replot '$Blambda' using 3:(\$2*sin(\$3*pi/180)) with lines

# set arrows
#jp=18
#j=16
##lmin=jp-j
#lmindeg=(lmin*(lmin+1)-j*(j+1)-jp*(jp+1))/(2*sqrt(j*(j+1)*jp*(jp+1)))
#amin=sqrt(lmin)/((jp+j)/2+1/2)
#set arrow from graph amin,0 to graph amin,100
#set arrow from graph lmindeg,0 to graph lmindeg,100

#set term postscript
#set output 'Bvals_16_18_'.strftime('%Y%a%b%d_%H%M%S.ps',time(0))
#replot
quit
" > deleteme2

gnuplot -persistent < deleteme2
