#!/bin/bash

# put the j and jp values in the right order
if [ $1 -gt $2 ]; then
    j=$1
    jp=$2
elif [ $1 -lt $2 ]; then
    j=$2
    jp=$1
fi

Btheta=normBtheta\_$j\_$jp\.dat
Blambda=normBlambda\_$j\_$jp\.dat
echo Theta file=$Btheta
echo Lambda file=$Blambda

# write the gnuplot commands
echo "
#!/usr/local/gnuplot
set term x11 0
set samples 10000

# B(theta)*sin(theta) vs theta
plot '$Btheta' using (\$1*180/pi):(\$2*sin(\$1)) with lines smooth csplines

# B[lambda]*sin(theta->lambda)
replot '$Blambda' using 3:(\$2*sin(\$3*pi/180)/200)
replot '$Blambda' using 3:(\$2*sin(\$3*pi/180)/200) with lines

# set arrows
amin=(sqrt($j-$jp)/(($j+$jp)/2+1/2))*180/pi
print 'amin=',amin,'deg'
#lmin=$j-$jp
#ldeg=(lmin*(lmin+1)-$j*($j+1)-$jp*($jp+1))/(-2*sqrt($j*($j+1)*$jp*($jp+1)))
set parametric
set trange [0:1]
set term x11 0
replot amin,t

#set term postscript
#set output 'Bvals_16_18_'.strftime('%Y%a%b%d_%H%M%S.ps',time(0))
#replot
quit
" > deleteme2

gnuplot -persistent < deleteme2
