#!/bin/bash

# remove all previous executables
rm dq2theta dqcalc pcc12
cd src

# compile fpp
gfortran -c fpp.for
gfortran -o fpp fpp.o

# list things to compile
tolink=(datetime ddiag2 dpackb stdio utility)
toexecute=(dq2theta dqcalc pcc12)

# end result is only .o files - used for the next set (toexecute)
for i in ${tolink[@]}; do
    # display status
    echo compiling $i...

    # run fpp on all files
    ./fpp < $i.for > $i.f
    
    # make .o files
    gfortran -c $i.f
done

for i in ${toexecute[@]}; do
    # display status
    echo compiling $i...

    # run fpp on all files
    ./fpp < $i.for > $i.f

    # make .o files
    gfortran -c $i.f

    # make executables
    gfortran -o $i $i.f utility.o datetime.o stdio.o dpackb.o
done

# move to usable file
mv dq2theta dqcalc pcc12 ../

# clean up
rm *.o
rm fpp
cd ..
echo DONE
