#!/bin/bash
filename=$1
outputfile=$2
if [ -z $filename ]; then
    echo Enter a valid file name.
fi
if [ "$(find $filename 2>/dev/null)" != "$filename" ]; then
    echo Enter a valid file name.
    exit
fi

if [ -z $outputfile ]; then
    outputfile=$(echo formatted_$filename\_$(date -I) | sed 's/-/_/g')
    echo $outputfile
fi
sed 's/\(.\{0,100\}\) \(.*\)/\1\n  \2/g' $filename >$outputfile
