#!/bin/bash
workdir=$1
origfile=$2
if [ "$workdir" = "" ] ; then
    echo bad input
    exit
else
    runprog=$(find . -name $workdir -nowarn)
    if [ "$runprog" != "./$workdir" ]; then
        echo directory not found
        echo Looking for $workdir in $(pwd)
        # add input validation for creating a directory and checking for subdirectory existence
        exit
    fi
fi
if [ "$origfile" = "" ]; then
    echo Enter an input file:
    read origfile
    if [ "$origfile" = "" ]; then
        echo File must not be null. Exiting.
        exit
    fi
fi

dj=1
dj=2
CTR=1
MAX=50
MAXdj=40
make
errfile=$workdir/errors.log
metafile=$workdir/metadata.txt
plotfile=$workdir/deleteme
dm=0

echo Writing to $workdir using $origfile

while [ $dj -le $MAXdj ]; do
    if [ $dj -lt 10 ]; then
        djstr=0$dj
    else
        djstr=$dj
    fi

    statdir=$workdir/Stats
    statfile=stats_dj$djstr\.dat
    echo \#j jp SCavg SCstd SCvar QMavg QMstd QMvar diffavg diffstd diffvar>$statdir/$statfile
    dthdir=$workdir/dtheta
    dthout=dtheta_dj$djstr\.dat
    echo j jp jbar dtheta discrete continuous Bmax\(a\) Bmax\(l\) appalpha> $dthdir/$dthout
    echo Running dj = $dj

    while [ $CTR -lt $(($MAX-$dj+1)) ]; do
        let dm=dm+1
        j=$CTR
        jp=$((CTR+$dj))

        # change so zeros are appended
        if [ $jp -lt 10 ]; then
            jpstr=0$jp
        else
            jpstr=$jp
        fi
        if [ $j -lt 10 ]; then
            jstr=0$j
        else
            jstr=$j
        fi

        # dqcalc
        blamdir=$workdir/Blambdas
        blamdat=Blambda_$jstr\_$jpstr.dat
        runprog=$(find $blamdir -name $blamdat -nowarn)
        origfile=Ep002mf5i-5015.blam
        if [ "$runprog" != "$blamdir/$blamdat" ]; then
            ./dqcalc newdata/$origfile $blamdir/$blamdat $j $jp
        fi

        # only proceed if the files were successfully created
        runprog=$(find $blamdir -name $blamdat -nowarn)
        if [ "$runprog" != "$blamdir/$blamdat" ]; then
            echo Error running dqcalc on j=$j,jp=$jp. Proceeding to next dataset >>$errfile
        else
            # dq2theta
            bthdir=$workdir/Bthetas
            bthdat=Btheta_$jstr\_$jpstr\_dj$djstr\.dat
            normblams=Blam_$jstr\_$jpstr\_dj$djstr\.dat
            read alphamin Bmaxa <<<$(./dq2theta $blamdir/$blamdat $bthdir/$bthdat)
            normdir=$workdir/Blams

            # only proceed if the files were successfully created
            runprog=$(find $bthdir -name $bthdat -nowarn)
            runprog1=$(find . -name $normblams -nowarn -maxdepth 1)
            if [ "$runprog" != "$bthdir/$bthdat" ] || [ "$runprog1" != "./$normblams" ]; then
                echo Error running dq2theta on j=$j,jp=$jp. Proceeding to next dataset >>$errfile
            else
                mv $normblams $normdir/$normblams

                # get the first angle (for lambda = lambdaMIN)
                # column 3, line 2
                lmindeg=$(cat $normdir/$normblams|sed -n '2p'|awk '{print $3}')
                Bmaxl=$(cat $normdir/$normblams|sed -n '2p'|awk '{print $4}') # normalized

                # calculate difference in theta
                dtheta=$(awk "BEGIN {print $lmindeg-$alphamin}")
                jbar=$(awk "BEGIN {print ($j+$jp)/2}")

                # write to file
                appalpha=$(awk "BEGIN {print (180/3.1415926)*(sqrt($jp-$j)/($jbar+1/2))}")
                echo $j $jp $jbar $dtheta $lmindeg $alphamin $Bmaxa $Bmaxl $appalpha>> $dthdir/$dthout
                outdir=$workdir/plots
                outputfile=BPlots_$jstr\_$jpstr\_dj$djstr\.ps

                # stats
                read SCavg SCstd SCvar QMavg QMstd QMvar <<<$(./main.out $j $jp $workdir)
                echo $j $jp $SCavg $SCstd $SCvar $QMavg $QMstd $QMvar #>>$errfile
                diffavg=$(awk "BEGIN {print "$SCavg"-"$QMavg"}")
                diffstd=$(awk "BEGIN {print "$SCstd"-"$QMstd"}")
                diffvar=$(awk "BEGIN {print "$SCvar"-"$QMvar"}")
                echo $j $jp $SCavg $SCstd $SCvar $QMavg $QMstd $QMvar $diffavg $diffstd $diffvar >>$statdir/$statfile

                # plot it
                # suppress visual output
                echo "#!/usr/local/gnuplot
                #        set term x11 0
                set samples 10000
                set term postscript

                plot '$normdir/$normblams' using 3:4 with impulse title 'Quantum Mechanical'
                replot '$bthdir/$bthdat' using 1:3 with lines smooth csplines title 'Semiclassical'

                set parametric
                set trange [0:$Bmaxa]
                #        set term x11 0
                replot $alphamin,t title 'alpha_min'
                replot $SCavg,t title 'SC average'
                replot $QMavg,t title 'QM average'
                set xlabel 'theta (deg)'
                set ylabel 'B'
                set title 'j=$j, jp=$jp'
                replot

                #        set term postscript
                set output '$outdir/$outputfile'
                replot
                quit
                " > $plotfile

                gnuplot < $plotfile> /dev/null
            fi
        fi
        exit

        let CTR=CTR+1
    done

    let dj=dj+1
    CTR=1
done

echo "Date: $(date)
Input file: $origfile
number of loops: $dm
Max=$MAX; Maxdj=$MAXdj
">$metafile

exit
