#!/bin/bash

dj=2
rm dtheta.dat
CTR=1
MAX=5

    echo j jp dtheta >> dtheta.dat
while [ $CTR -lt $MAX ]; do
    j=$CTR
    jp=$(($CTR+2))
    echo J VALUES: $j $jp


    # dqcalc
    blamdat=Blambda_$j\_$jp.dat
    echo creating $blamdat ...
    ./dqcalc newdata/Ep002mf5i-50b.blam $blamdat $j $jp

    # dq2theta
    if [ $jp -lt 10 ]; then
        bthdat=Btheta_0$j\_0$jp.dat
        normblams=Blam_0$j\_0$jp.dat
    elif [ $j -lt 10 ]; then
        bthdat=Btheta_0$j\_$jp.dat
        normblams=Blam_0$j\_$jp.dat
    else
        bthdat=Btheta_$j_$jp.dat
        normblams=Blam_$j\_$jp.dat
    fi

    echo creating $bthdat ...
    echo creating $normblams ...
    read alphamin Bmax <<<$(./dq2theta $blamdat $bthdat)

    # get the first angle (for lambda = lambdaMIN)
    dtheta=$(cat $normblams|sed -n '2p'|awk '{print $3}')
    echo $j $jp $dtheta >> dtheta.dat

    # main
    #./main.out $j $jp

    # plot it
    echo "#!/usr/local/gnuplot
    set term x11 $jctr
    set samples 10000

    plot '$normblams' using 3:4 with impulse
    replot '$bthdat' using 1:3 with lines smooth csplines

    set parametric
    set trange [0:$Bmax]
    set term x11 $jctr
    replot $alphamin,t
    " > deleteme2

    #gnuplot -persistent < deleteme2
    #cat deleteme2

    let CTR=CTR+1
done

