#!/bin/bash
#j=starting smaller j value
#jp=j+dj
#range
#   j - all dj's possible for j {j,j+range} ; range gives jpmax
#   dj - all j,jp combinations for dj {dj,dj+range} ; range gives djmax

args='getopt j:p:d:r $*'
j=0;jp=0;dj=0
echo parsing...
for i
do
    case "$i" in
        -j) shift; echo "j=$1";shift
            ;;
        -p) shift; echo "jp=$1";shift
            ;;
        -d) shift; echo "dj=$1";shift
            ;;
        -r) shift; echo "range=$1";shift
    esac
done
jmin=$j
#jmax=$(awk 'BEGIN {print '$j'+'$range'}')

if [ $dj -ne $(($jp-$j)) ] ; then
    echo bad input values
    echo dj=$dj; j=$j; jp=$jp
    exit
fi
exit

j=16
jp=18
if [ $jp -lt 10 ]; then
    jpstr=0$jp
else
    jpstr=$jp
fi
if [ $j -lt 10 ]; then
    jstr=0$j
else
    jstr=$j
fi
blamdir=Run2Results/Blambdas/
blamdat=Blambda_$jstr\_$jpstr\.dat

foo=$(find $blamdir -name $blamdat -nowarn)
if [ "$foo" != "$blamdir$blamdat" ]; then
    echo not here
else
    echo found it
fi


myflag=0
if [ $myflag ]; then
    echo 0
else
    echo 1
fi
#https://sites.google.com/site/antialamas/awkoneliners
cat deleteme | awk '{sum+=#1} END {print sum}'
awk '{sum=sum+$1}END{print sum}' deleteme
awk 'BEGIN{max=0}{if($1>max)max=$1}END{print max}' deleteme
