#!/bin/bash

dj=1
max=50

while [ $dj -lt $max ]; do
    if [ $dj -lt 10 ]; then
        djstr=0$dj
    else
        djstr=$dj
    fi

    echo "
    set samples 10000
    plot 'stats_dj$djstr.dat' using 1:3 with lines
    " > plotme

    gnuplot -persistent < plotme
    let dj=dj+1
done
