#!/bin/bash

dj=1
max=50

while [ $dj -lt $max ]; do
    if [ $dj -lt 10 ]; then
        djstr=0$dj
    else
        djstr=$dj
    fi

    infile=stats_dj$djstr.dat
    outfile=avg_std_dj$djstr.eps

    echo "
    set term postscript eps enhanced
    set samples 10000
    set xrange [0:50]
    set yrange [0:100]
    plot '$infile' using ((\$1+\$2)/2):3 with lines smooth csplines title 'SCavg fit'
    replot '$infile' using ((\$1+\$2)/2):3 title 'SCavg'
    replot '$infile' using ((\$1+\$2)/2):6 with lines smooth csplines title 'QMavg fit'
    replot '$infile' using ((\$1+\$2)/2):6 title 'QMavg'
    replot '$infile' using ((\$1+\$2)/2):4 with lines smooth csplines title 'SCstd fit'
    replot '$infile' using ((\$1+\$2)/2):4 title 'SCavg'
    replot '$infile' using ((\$1+\$2)/2):7 with lines smooth csplines title 'QMstd fit'
    replot '$infile' using ((\$1+\$2)/2):7 title 'QMavg'
    set xlabel 'jbar';set ylabel '{/Symbol a} (deg)'; set title 'Avg. and Std., dj=$dj'
    set output '$outfile'
    replot
    " > plotme

    gnuplot < plotme >/dev/null 2>&1
    gv $outfile >/dev/null 2>&1
#    gv avgdiffs_dj$djstr.eps >/dev/null 2>&1

    let dj=dj+1
done
