#!/bin/bash

# type: th or dm
# c: dj or jb
#
# defaults: -t th -c dj
args='getopt t:c $*'
thdm=th
xconst=dj
for i
do
    case "$i" in 
        -t) shift; thdm=$1; shift
            ;;
        -c) shift; xconst=$1; shift
    esac
done

djlist=(1 2 3 4 5 6 7 8 9 10)
jblist=(5 10 20 30 35)
prefix=He

if [ "$xconst" = "dj" ]; then
    echo dj held constant
    for dj in ${djlist[*]}; do
        filename=$prefix\_w$thdm\_*dj$dj\.ps
        for i in $(find $filename); do
            gv $i -scale 3 2>/dev/null &
        done
        echo next dj?
        read goahead
        if [[ "$goahead" = n* ]] || [[ "$goahead" = exit ]] || [[ "$goahead" = quit ]]; then
            exit
        fi
    done
elif [ "$xconst" = "jb" ]; then
    echo jbar held constant
    for jb in ${jblist[*]}; do
        for dj in ${djlist[*]}; do
            if [ $(($dj%2)) -eq 0 ]; then #even
                jdiff=$(($dj/2))
                j=$(($jb-$jdiff))
                jp=$(($jb+$jdiff))
            else
                jdiff=$(($dj/2))
                j=$(($jb-$jdiff))
                jp=$(($jb+$jdiff+1))
            fi
            if [ $j -ne 0 ]; then
                filename=$prefix\_w$thdm\_j$j\jp$jp\_dj$dj\.ps
                echo $filename
                gv $filename -scale 3 2>/dev/null &
            fi
        done
        echo next jbar?
        read goahead
        if [[ "$goahead" = n* ]] || [[ "$goahead" = exit ]] || [[ "$goahead" = quit ]]; then
            exit
        fi
    done
fi
exit
