#!/bin/bash
Hedir=../He2Results/Stats
Ardir=../Ar1Results/Stats

jlist=(2 3 8 9)
for i in ${jlist[*]}; do
    filename=avg_std_dj0$i.eps
    cp $Hedir/$filename ./He_$filename
    cp $Ardir/$filename ./Ar_$filename
done
