#!/bin/bash

PI=3.14159266

dj=1
ctr=1
max=50

outfile=allavg.dat
foofile=foo

echo \#abar\(disc\) = discrete/summation expectation value of a >$outfile
echo \#abar\(dsimp\) = expecation value of a computed by dsimp >>$outfile
echo \#d\(abar\) = abar\(disc\) - abar\(dsimp\) >>$outfile
echo \#dalpha  = standard deviation, sqrt\(\<a^2\>-\<a\>^2\) >>$outfile
echo \# >>$outfile

echo \#dj jbar abar\(disc\) abar\(dsimp\) d\(abar\) dalpha >>$outfile

while [ $dj -le $(($max-1)) ]; do
    echo analyzing dj = $dj
    if [ $dj -lt 10 ]; then
        djstr=0$dj
    else
        djstr=$dj
    fi
    infile=../stats_dj$djstr\.dat

    while [ $ctr -lt $(($max-$dj+1)) ]; do
        jp=$(($ctr+$dj))
        checkfile=checkstats_$ctr\_$jp\.dat

        line=$(($ctr+1)) # line of continuous function file

        # selects the j+1 line, 3rd column of the dsimp average
        abarc=$(sed -n "$line"'p' $infile|awk '{print $3}')

        # computes the discrete average
        abardrad=$(sed '/#/d' $checkfile|awk '{sum+=$1*$3; sum2+=$3} END {print sum/sum2}')
        abarddeg=$(awk "BEGIN {print "$abardrad"*180/"$PI"}")

        # compute discrete delta(alpha) = dalph
        a2bardrad=$(sed '/#/d' $checkfile|awk '{sum+=$2*$3; sum2+=$3} END {print sum/sum2}')
        a2barddeg=$(awk "BEGIN {print "$a2bardrad"*180/"$PI"}")
        dalphrad=$(awk "BEGIN {print sqrt("$a2bardrad"-"$abardrad"*"$abardrad")}")
        dalphdeg=$(awk "BEGIN {print "$dalphrad"*180/"$PI"}")

        diff=$(awk "BEGIN {print "$abarc"-"$abarddeg"}")
        jbar=$((($jp+$ctr)/2))
        echo $dj $jbar $abarc $abarddeg $diff $dalphdeg >>$outfile

        let ctr=ctr+1
    done

    let ctr=1
    let dj=dj+1
done

#echo "plot '$outfile' using 2:(\$3-\$4)" > foofile
#gnuplot -persistent < foofile
#rm foofile

#for i in $(ls checkstats_*); do
#    abar=$(sed '/#/d' $i|awk '{sum+=$1*$3; sum2+=$3} END {print (180/$PI)*sum/sum2}')
#    echo $abar >>$outfile
#done
