#!/bin/bash

PI=3.14159266

dj=1
ctr=1
max=50

outfile=allavg.dat
foofile=foo

#echo dj jbar discrete dsimp >$outfile

while [ $dj -le $(($max-1)) ]; do
    echo analyzing dj = $dj
    if [ $dj -lt 10 ]; then
        djstr=0$dj
    else
        djstr=$dj
    fi
    infile=../stats_dj$djstr\.dat

    while [ $ctr -lt $(($max-$dj+1)) ]; do
        jp=$(($ctr+$dj))
        checkfile=checkstats_$ctr\_$jp\.dat

        line=$(($ctr+1)) # line of continuous function file

        # selects the j+1 line, 3rd column of the dsimp average
        abarc=$(sed -n "$line"'p' $infile|awk '{print $3}')

        # computes the discrete average
        abard=$(sed '/#/d' $checkfile|awk '{sum+=$1*$3; sum2+=$3} END {print (180/$PI)*sum/sum2}')

        # compute discrete delta(alpha) = dalph
        dalph=$(awk '{print sqrt(4)}')
        echo $dalph

        jbar=$((($jp+$ctr)/2))
#        echo $dj $jbar $abarc $abard >>$outfile

        let ctr=ctr+1
    done

    let ctr=1
    let dj=dj+1
done

#echo "plot '$outfile' using 2:(\$3-\$4)" > foofile
#gnuplot -persistent < foofile
#rm foofile

#for i in $(ls checkstats_*); do
#    abar=$(sed '/#/d' $i|awk '{sum+=$1*$3; sum2+=$3} END {print (180/$PI)*sum/sum2}')
#    echo $abar >>$outfile
#done
