#!/bin/bash

dj=1
max=50

while [ $dj -lt $max ]; do
    if [ $dj -lt 10 ]; then
        djstr=0$dj
    else
        djstr=$dj
    fi

    echo "
    set term postscript eps enhanced
    set samples 10000
    set xrange [0:50]
    set yrange [0:100]
    plot 'stats_dj$djstr.dat' using ((\$1+\$2)/2):3 with lines smooth csplines title 'SCavg'
    replot 'stats_dj$djstr.dat' using ((\$1+\$2)/2):6 title 'QMavg'
    set xlabel 'jbar';set ylabel '{/Symbol a} (deg)'; set title 'He: <{/Symbol a}>, dj=$dj'
    set output 'avg_dj$djstr.eps'
    replot

#    set term postscript eps enhanced
#    set samples 10000
#    set xrange [0:50]
#    set yrange [-3:3]
#    plot 'stats_dj$djstr.dat' using ((\$1+\$2)/2):9 with lines smooth csplines title 'diffs'
#    replot 'stats_dj$djstr.dat' using ((\$1+\$2)/2):9 title ''
#    set xlabel 'jbar';set ylabel '{/Symbol D}{/Symbol a} (deg)'; set title 'He: <{/Symbol a}> diffs, dj=$dj'
#    set output 'avgdiffs_dj$djstr.eps'
#    replot
    " > plotme

    gnuplot < plotme >/dev/null 2>&1
#    gv avg_dj$djstr.eps >/dev/null 2>&1
#    gv avgdiffs_dj$djstr.eps >/dev/null 2>&1

    let dj=dj+1
done
