#!/bin/bash

for i in $(find *ps); do
    fname=$(echo $i | sed 's/\(^.*dj[0-9][0-9]\)\(\.ps\)/\1/g')
    gs -sDEVICE=jpeg -sOutputFile=$fname\.jpg - < $fname\.ps >/dev/null
done

for i in $(find *.jpg); do
    gnome-open $i 2>/dev/null 
done
