#!/bin/bash

#outputfile=Dtheta_all.dat

#echo dj jbar Bmax >$outputfile

ctr=0
for i in $(ls dtheta_dj*dat); do
    rm foo
    echo $i
    if [ $ctr -gt 15 ]; then
        echo "#!/usr/local/gnuplot
        plot '$i' u 3:7
        replot '$i' u 3:7 with lines
        quit" > foo
        gnuplot -persistent < foo
    elif [ $ctr -gt 30 ]; then
        exit
    fi
        let ctr=ctr+1
    #    sed '0,/^.*$/d' $i|awk '{print $2-$1 " " $3 " " $7}'>>$outputfile
done
