#!/bin/bash

#outputfile=Dtheta_all.dat

#echo dj jbar Bmax >$outputfile

ctr=0
for i in $(ls dtheta_dj*dat); do
    rm foo
    if [ $ctr -gt 0 ]; then
        echo "#!/usr/local/gnuplot
        set term postscript
        set xrange [0:50]
        plot '$i' u 3:7
        replot '$i' u 3:7 with lines smooth csplines
        set xlabel 'jbar'; set ylabel 'Bmax';set title 'Bmax vs. jbar for $i';
        replot
        set output 'Bmax_dj$(($ctr+1)).ps'
        replot
        quit" > foo
        gnuplot < foo >/dev/null 2>&1
    elif [ $ctr -gt 30 ]; then
        exit
    fi
        let ctr=ctr+1
    #    sed '0,/^.*$/d' $i|awk '{print $2-$1 " " $3 " " $7}'>>$outputfile
done
