#!/bin/bash

MAX=40
dj=1
odir=../../He2Results/dtheta
while [ $dj -le $MAX ]; do
    if [ $dj -lt 10 ]; then
        djstr=0$dj
    else
        djstr=$dj
    fi

    i=dtheta_dj$djstr.dat
    ofile=$odir/$i
    outfile=compBmax_dj$djstr.ps
    rm foo

    echo "#!/usr/local/gnuplot
    set term postscript
    set xrange [0:50]
    plot '$i' u 3:7 with lines smooth csplines title 'lmax=15'
    replot '$ofile' u 3:7 with lines smooth csplines title 'lmax=10'
    set xlabel 'jbar'; set ylabel 'Bmax';set title 'Bmax vs. jbar for $i';
    replot
    set output '$outfile'
    replot
    quit" > foo
    gnuplot < foo >/dev/null 2>&1

    echo dj jbar B\(l=15\) B\(l=10\) diff >barfile
    awk 'NR==FNR{a[NR]=$7;next} {print '$djstr',$3,a[FNR],$7,a[FNR]-$7}' $i $ofile|sed '/j/d'>>barfile
    rm foo
    echo "#!/usr/local/gnuplot
    set term x11 0
    set xrange [0:50]
    plot 'barfile' u 2:(200*abs(\$5)/(\$3+\$4))
    set xlabel 'jbar'; set ylabel '% diff Bmax';set title 'l=15-l=10 Bmax vs. jbar for $i';
    replot
    set term postscript
    set output 'diff$outfile'
    replot
    quit" > foo
    gnuplot < foo >/dev/null 2>&1

    let dj=dj+1
done
