#!/bin/bash
dm=dm.dat
j=1
dj=4
max=50
max=40
rm $dm

echo \#jbar theta B >$dm
while [ $j -le $(($max-$dj)) ]; do
    jp=$(($dj+$j))
    if [ $dj -lt 10 ]; then
        djstr=0$dj
    else
        djstr=$dj
    fi
    if [ $j -lt 10 ]; then
        jstr=0$j
    else
        jstr=$j
    fi
    if [ $jp -lt 10 ]; then
        jpstr=0$jp
    else
        jpstr=$jp
    fi

    sed '/#/d' Btheta_$jstr\_$jpstr\_dj$djstr.dat|awk '{print ('$j'+'$jp')/2 " "$1 " " $2}'>>$dm
    let j=j+1
done

echo "
set term x11 0
plot '$dm' u 2:1:(\$3*sin(\$2*pi/180)) with image
set xlabel '{/Symbol T} (deg)'
set ylabel 'jbar'
#set title '{/Symbol D}j=4 He'
set title '{/Symbol D}j=4 Ar'
replot
set term postscript eps enhanced
set output 'plot.eps'
replot
" >plotscript

gnuplot -persistent <plotscript #>/dev/null 2>&1
rm plotscript
