#!/bin/bash

dj=1
max=50

while [ $dj -lt $max ]; do
    if [ $dj -lt 10 ]; then
        djstr=0$dj
    else
        djstr=$dj
    fi

    echo "
    set term postscript eps enhanced
    set samples 10000
    set xrange [0:50]
    set yrange [0:100]
    plot 'stats_dj$djstr.dat' using (($1+$2)/2):4 with lines smooth csplines title 'SCvar'
    replot 'stats_dj$djstr.dat' using (($1+$2)/2):7 title 'QMvar'
    set xlabel 'jbar';set ylabel 'd{/Symbol a}^2 (deg)'; set title 'He: Variance, dj=$dj'
    set output 'var_dj$djstr.eps'
    replot

    set term postscript
    set samples 10000
    set xrange [0:50]
    set yrange [-3:10]
    plot 'stats_dj$djstr.dat' using (($1+$2)/2):10 with lines smooth csplines title 'diffs'
    replot 'stats_dj$djstr.dat' using (($1+$2)/2):10 title ''
    set output 'vardiffs_dj$djstr.eps'
    set xlabel 'jbar';set ylabel '{/Symbol D}d{/Symbol a}^2 (deg)'; set title 'He: Variance diffs, dj=$dj'
    replot
    " > plotme

    gnuplot < plotme >/dev/null 2>&1
#    gv var_dj$djstr.eps >/dev/null 2>&1
#    gv vardiffs_dj$djstr.eps >/dev/null 2>&1

    let dj=dj+1
done
